# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       GhostCluster
Summary:    Automotive Meter Cluster Application
Version:    0.2013.4.4
Release:    1
Group:      Applications/System
License:    Apache 2.0
URL:        http://www.tizen.org
Source0:    %{name}-%{version}.tar.gz
Source100:  gc-install
Requires:   automotive-message-broker-plugins-websocket
Requires:   wrt-installer
BuildRequires: zip

%description
Example guage cluster for tizen ivi

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre


make widget


# >> build post
# << build post
%install
rm -rf %{buildroot}

%make_install

mkdir -p %{buildroot}/etc/rc.d/init.d
install -m 755 %{SOURCE100}  %{buildroot}/etc/rc.d/init.d/gc-install
mkdir -p %{buildroot}/etc/rc.d/rc3.d
ln -s ../init.d/gc-install %{buildroot}/etc/rc.d/rc3.d/S62gc-install
mkdir -p %{buildroot}/etc/rc.d/rc5.d
ln -s ../init.d/gc-install %{buildroot}/etc/rc.d/rc5.d/S62gc-install

%post

wrt-installer -if %{_datadir}/GhostCluster/GhostCluster.wgt

# >> install post
# << install post






%files
%defattr(-,root,root,-)
%{_datadir}/GhostCluster
%{_sysconfdir}/rc.d/init.d/gc-install
%{_sysconfdir}/rc.d/rc3.d/S62gc-install
%{_sysconfdir}/rc.d/rc5.d/S62gc-install

#%{_datadir}/applications/GhostCluster.desktop
#%{_datadir}/pixmaps/GhostCluster.png
# >> files
# << files


